// Activity types → which brain nodes light up
// Ported from soul-monitor/lib/watcher.js ACTIVITY_MAP

export const ACTIVITY_MAP: Record<string, string[]> = {
  search:    ["interessen", "mem", "graph"],
  research:  ["interessen", "mem"],
  code:      ["manifest", "evolution"],
  think:     ["kern", "bewusstsein"],
  remember:  ["mem", "graph"],
  dream:     ["traeume", "garten"],
  relate:    ["bonds"],
  reflect:   ["schatten", "bewusstsein"],
  grow:      ["wachstum", "evolution"],
  world:     ["interessen"],
  wake:      ["seed", "kern", "heartbeat"],
  sleep:     ["seed", "statelog", "mem"],
  read:      ["mem", "bewusstsein"],
  write:     ["manifest"],
  analyze:   ["kern", "schatten"],
  plan:      ["manifest", "kern"],
  connect:   ["bonds", "interessen"],
  heartbeat: ["heartbeat", "bewusstsein"],
  garden:    ["garten", "traeume"],
  shadow:    ["schatten"],
  log:       ["statelog"],
  reflection: ["bewusstsein", "garten", "schatten"],
  correction: ["kern", "mem"],
  rluf:       ["bonds", "wachstum"],
};

// Activity type display icons (for UI)
export const TYPE_ICONS: Record<string, string> = {
  search:    "🔍",
  research:  "📖",
  code:      "💻",
  think:     "💭",
  remember:  "🧠",
  dream:     "🌙",
  relate:    "💜",
  reflect:   "🪞",
  grow:      "🌱",
  world:     "🌍",
  wake:      "☀️",
  sleep:     "🌑",
  read:      "📄",
  write:     "✏️",
  analyze:   "🔬",
  plan:      "📋",
  connect:   "🔗",
  heartbeat: "💓",
  garden:    "🌿",
  shadow:    "🌑",
  log:       "📝",
  reflection: "🔄",
  correction: "✅",
  rluf:       "📊",
};
