name: SoulApp
options:
  bundleIdPrefix: dev.projectsoul
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
targets:
  SoulApp:
    type: application
    platform: iOS
    sources:
      - SoulApp
    settings:
      base:
        INFOPLIST_FILE: SoulApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.projectsoul.soulapp
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
